alertmanager_version: "0.27.0"
alertmanager_user: "alertmanager"
alertmanager_group: "alertmanager"
smtp_host: "email-smtp.us-west-2.amazonaws.com"
smtp_port: "587"
smtp_user: "smtp_user"
smtp_password: "smtp_password"
slack_api_url: "https://hooks.slack.com/services/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"
slack_channel: "#prometheus"
recipient_email: "ayoxdele@gmail.com"